const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  signup: (credentials: any) => ipcRenderer.invoke('auth:signup', credentials),
  login: (credentials: any) => ipcRenderer.invoke('auth:login', credentials),
  loginSuccess: () => ipcRenderer.send('auth:success'),
  createCheckoutSession: (userId: any) => ipcRenderer.invoke('payment:checkout', { userId }),
  createAdminSession: () => ipcRenderer.invoke('admin:create-session'),
  createFreeTrialSession: () => ipcRenderer.invoke('session:create-free-trial'),
  getCurrentUser: () => ipcRenderer.invoke('auth:get-user'),
  getStripePublishableKey: () => ipcRenderer.invoke('payment:get-publishable-key'),
  getSessionStatus: (userId: any) => ipcRenderer.invoke('session:get-status', { userId }),
  startSession: (userId: any) => ipcRenderer.invoke('session:start', { userId }),
  sendChatMessage: (data: any) => ipcRenderer.send('chat:send', data),
  onChatStream: (callback: any) => ipcRenderer.on('chat:stream-chunk', (_event: any, data: any) => callback(data)),
  removeAllListeners: (channel: string) => ipcRenderer.removeAllListeners(channel),
  captureScreen: () => ipcRenderer.invoke('capture-screen'),
  uploadAudio: (uploadData: any) => ipcRenderer.invoke('audio:upload', uploadData),
  openExternalUrl: (url: string) => ipcRenderer.invoke('open-external-url', url),
  loadPaymentPage: () => ipcRenderer.send('nav:payment'),
  loadStartSessionPage: () => ipcRenderer.send('nav:start-session'),
  loadMainAppPage: () => ipcRenderer.send('nav:main-app'),
  checkForUpdates: () => ipcRenderer.invoke('app:check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('app:download-update'),
  installUpdate: () => ipcRenderer.invoke('app:install-update'),
  getAppVersion: () => ipcRenderer.invoke('app:get-version'),
  // Update event listeners
  onUpdateAvailable: (callback: any) => ipcRenderer.on('update:available', (_event: any, info: any) => callback(info)),
  onUpdateNotAvailable: (callback: any) => ipcRenderer.on('update:not-available', (_event: any, info: any) => callback(info)),
  onUpdateError: (callback: any) => ipcRenderer.on('update:error', (_event: any, error: any) => callback(error)),
  onUpdateDownloadProgress: (callback: any) => ipcRenderer.on('update:download-progress', (_event: any, progress: any) => callback(progress)),
  onUpdateReadyToInstall: (callback: any) => ipcRenderer.on('update:ready-to-install', (_event: any, info: any) => callback(info)),
}); 